using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using API.Models; // For using Citation model and CitationType enum
using API.Services; // For using CitationService class

namespace API.Controllers
{
    [ApiController]
    [Route("api/citations")]
    public class CitationController : ControllerBase // Use ControllerBase for API controllers without view support
    {
        private readonly CitationService _citationService;

        // Constructor for dependency injection of CitationService
        public CitationController(CitationService citationService)
        {
            _citationService = citationService;
        }

        [HttpGet]
        public IActionResult GetAllCitations()
        {
            var citations = _citationService.GetAllCitations();
            
            if (citations == null || citations.Count == 0)
            {
                return NotFound(new { message = "No citations found" });
            }

            return Ok(new
            {
                message = "Success get all citations",
                data = citations
            });
        }

        [HttpGet("{id}")]
        public IActionResult GetCitationById(Guid id)
        {
            var citation = _citationService.GetCitationById(id);

            if (citation == null)
            {
                return NotFound(new { message = "Citation not found" });
            }

            return Ok(new
            {
                message = "Success get citation by ID",
                data = citation
            });
        }

        [HttpGet("document/{documentId}")]
        public IActionResult GetCitationsByDocumentId(Guid documentId)
        {
            if (documentId == Guid.Empty)
            {
                return BadRequest(new { message = "Document ID cannot be empty." });
            }

            var citations = _citationService.GetCitationsByDocumentId(documentId);
            if (citations == null || !citations.Any())
            {
                return NotFound(new { message = "No citations found for the specified document ID" });
            }

            if (citations.Count() > 100)
            {
                return BadRequest(new { message = "Too many citations found. Please refine your search." });
            }

            return Ok(new
            {
                message = "Success get citations by document ID",
                data = citations
            });
        }

        [HttpPost]
        public IActionResult CreateCitation([FromBody] Citation newCitationRequest)
        {
            if (newCitationRequest == null)
            {
                return BadRequest(new { message = "Citation request cannot be null." });
            }
                
            // Ensure the ID is not set in the request body, as it will be generated by the service
            if (newCitationRequest.Id != Guid.Empty)
            {
                return Unauthorized(new { message = "ID should not be set in the request body. It will be generated automatically." });
            }
                
            // Basic validation for required fields
            if (string.IsNullOrWhiteSpace(newCitationRequest.Title) || string.IsNullOrWhiteSpace(newCitationRequest.Author))
            {
                return BadRequest(new { message = "Title and Author are required." });
            }

            var createdCitation = _citationService.CreateCitation(
                newCitationRequest.Type,
                newCitationRequest.Title,
                newCitationRequest.Author,
                newCitationRequest.Pages,          // New
                newCitationRequest.Volume,         // New
                newCitationRequest.Issue,          // New
                newCitationRequest.URL,            // New
                newCitationRequest.AccessURL,      // New
                newCitationRequest.AccessLocation, // New
                newCitationRequest.PublicationInfo,
                newCitationRequest.Publisher,      // New
                newCitationRequest.PublicationDate,
                newCitationRequest.PublisherLocation, // New
                newCitationRequest.AccessDate,
                newCitationRequest.DOI,
                newCitationRequest.FK_DocumentId // documentId is now optional in service, but still passed from request
            );

            if (createdCitation == null)
            {
                return BadRequest(new { message = "Failed to create citation. Please check the provided data." });
            }

            return CreatedAtAction(nameof(GetCitationById), new { id = createdCitation.Id }, new
            {
                message = "Success create new citation",
                data = createdCitation
            });
        }

        [HttpPut("{id}")]
        public IActionResult UpdateCitation(Guid id, [FromBody] Citation updatedCitationRequest)
        {
            // Check if the request body is null
            if (updatedCitationRequest == null)
            {
                return BadRequest(new { message = "Citation request cannot be null." });
            }

            // Ensure the ID in the route matches the ID in the request body (if provided)
            if (id != updatedCitationRequest.Id && updatedCitationRequest.Id != Guid.Empty)
            {
                return Unauthorized(new { message = "Mismatched ID in route and request body." });
            }

            // Basic validation for required fields
            if (string.IsNullOrWhiteSpace(updatedCitationRequest.Title) || string.IsNullOrWhiteSpace(updatedCitationRequest.Author))
            {
                return BadRequest(new { message = "Title and Author are required." });
            }

            var updatedCitation = _citationService.UpdateCitation(
                id, // Use the ID from the route
                updatedCitationRequest.Type,
                updatedCitationRequest.Title,
                updatedCitationRequest.Author,
                updatedCitationRequest.Pages,          // New
                updatedCitationRequest.Volume,         // New
                updatedCitationRequest.Issue,          // New
                updatedCitationRequest.URL,            // New
                updatedCitationRequest.AccessURL,      // New
                updatedCitationRequest.AccessLocation, // New
                updatedCitationRequest.PublicationInfo,
                updatedCitationRequest.Publisher,      // New
                updatedCitationRequest.PublicationDate,
                updatedCitationRequest.PublisherLocation, // New
                updatedCitationRequest.AccessDate,
                updatedCitationRequest.DOI
            );

            if (updatedCitation == null)
            {
                return NotFound(new { message = "Citation not found or update failed" });
            }

            return Ok(new
            {
                message = "Success to update citation",
                data = updatedCitation
            });
        }

        [HttpDelete("{id}")]
        public IActionResult DeleteCitation(Guid id)
        {
            // Validate the ID
            if (id == Guid.Empty)
            {
                return BadRequest(new { message = "Citation ID cannot be empty." });
            }

            var isDeleted = _citationService.DeleteCitation(id);
            if (!isDeleted)
            {
                return NotFound(new { message = "Citation not found" });
            }
            return Ok(new
            {
                message = "Citation has been deleted"
            });
        }

        [HttpGet("{id}/apa")]
        public IActionResult GetCitationApaStyle(Guid id)
        {
            // Validate the ID
            if (id == Guid.Empty)
            {
                return BadRequest(new { message = "Citation ID cannot be empty." });
            }

            var formattedCitation = _citationService.GetFormattedCitationAPA(id);
            if (formattedCitation == null)
            {
                return NotFound(new { message = "Citation not found or could not be formatted." });
            }

            return Ok(new
            {
                message = "Success get APA style citation",
                data = formattedCitation
            });
        }
    }
}